### ISSUE TITLE
[JS][thinphp.js]setFormError - selection of the fmsg span

### ISSUE THREAD

**Issue by bmaingret** [ngduc/Thin-PHP-Framework#12]
Hi,
I don't know if it is the behavior researched, but when you put : 
97.  $(formId+' :input[name='+fieldName+'] ~ span.fmsg').html('&nbsp;'+errMsg+'&nbsp;');
98.  $(formId+' :input[name='+fieldName+'] ~ span.fmsg').fadeIn('slow');
You will change every fmsg following the fieldName input. Perhaps it would be better to put 
- span.fmsg (cf. http://api.jquery.com/next-adjacent-Selector/ )
  so that only the fmsg following directly the input would be affected.
  But again, maybe you only put one fmsg per form, in which case it would work :)

**Comment by ngduc** [comment]
Good catch! You are right.
According to jQuery syntax:
"~" is the Next Siblings Selector (“prev ~ siblings”) - selects all sibling elements that follow after the "prev" element, have the same parent, and match the filtering "siblings" selector.

So, input field & its "fmsg" span should be together under their parent.

This is the demo page & I think it works with multiple errors because it set errors from top, down.
http://demo.thinphp.com/contact-us

I will investigate more & fix it. Thanks again :)

**Comment by ngduc** [comment]
Fixed in this commit:
https://github.com/ngduc/Thin-PHP-Framework/commit/a920978bdc5f2fd04d27bfef4f8b427d1aa3b28f

Thanks again seven-up! :)

btw, a new version has just been released v0.55
