### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by SorenA** [ngduc/Thin-PHP-Framework#8]
nvm

**Comment by davidyew** [comment]
Hi SorenA,

I am unsure about this.
But overall the framework does work and is fantastic!
I think it is faster than DooPHP http://doophp.com/ due to its
'thin-ness'! :)

I had Gzip turned on for added performance.

Assuming you have gzip supported webhost / website,
under dispatcher.php add the following at the beginning.

ini_set("zlib_output_compression","On");
header('Content-Encoding: gzip');
if(!ob_start("ob_gzhandler")) ob_start();

I have tested it on Ubuntu and Firefox 6.0, which gives fast rendering.

regards
David Yew

**Comment by ngduc** [comment]
Talking about gzip,
I have just fixed a problem in "outputJson" function in "main_util.php" using ini_set.

Thank you David
